Micro.Web/Controllers/AuthController.cs
using Micro.Web.Models.Dto;
using Micro.Web.Services.IServices;
using Micro.Web.Utility;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Runtime.CompilerServices;
using System.Security.Claims;

namespace Micro.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _ITokenProvider;
        public AuthController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
            _ITokenProvider = tokenProvider;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Register()
        {
            var Rolelist = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleCustomer, Value = SD.RoleCustomer},
                new SelectListItem { Text=SD.RoleAdmin, Value = SD.RoleAdmin}
            };
            ViewBag.RoleList = Rolelist;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterationRequestDto registerationRequestDto)
        {
            ResponseDto? result1 = await _authService.Register(registerationRequestDto);
            ResponseDto? result2 = await _authService.AssignRole(registerationRequestDto);
            return RedirectToAction(nameof(Login));
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDto loginRequestDto)
        {
             ResponseDto responseDto = await _authService.Login(loginRequestDto);
             
            if(responseDto.IsSuccess && responseDto.Result != null)
            {
                LoginResponseDto? loginResponseDto = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(responseDto.Result));
                if (loginResponseDto != null)
                {
                    await SignInUser(loginResponseDto);
                    string token = loginResponseDto.Token;
                    _ITokenProvider.SetToken(token);
                    return RedirectToAction("Index","Home");
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();
            _ITokenProvider.ClearedToken();
            return RedirectToAction("Index", "Home");
        }
        private async Task SignInUser(LoginResponseDto loginResponseDto)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var jwt = tokenHandler.ReadJwtToken(loginResponseDto.Token);
            var claims = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            claims.AddClaim(new Claim(JwtRegisteredClaimNames.Email,
                jwt.Claims.FirstOrDefault(u=>u.Type == JwtRegisteredClaimNames.Email).Value));
            claims.AddClaim(new Claim(JwtRegisteredClaimNames.Sub,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));
            claims.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
                jwt.Claims.FirstOrDefault(u=>u.Type == JwtRegisteredClaimNames.Name).Value
                ));
            claims.AddClaim(new Claim(ClaimTypes.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value
                ));
            claims.AddClaim(new Claim(ClaimTypes.Role,
                jwt.Claims.FirstOrDefault(u => u.Type == "role").Value
                ));
            var principal = new ClaimsPrincipal(claims);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme , principal);   
        }
    }
}

Micro.Web/Controllers/CategoryController.cs
using Micro.Web.Models.Dto;
using Micro.Web.Services.IServices;
using Micro.Web.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Micro.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _CategoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _CategoryService = categoryService;
        }
        [Authorize(Roles = SD.RoleCustomer)]
        public async Task<IActionResult> Index()
        {
            ResponseDto response = await _CategoryService.Get();
            if (response.IsSuccess && response.Result != null)
            {
                List<CategoryDto> categories = JsonConvert.DeserializeObject<List<CategoryDto>>(response.Result.ToString());
                return View(categories);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CategoryDto categoryDto)
        {
            _CategoryService.Create(categoryDto);
            return View();
        }
        [HttpGet("[controller]/Update/{categoryId?}")]
        public async Task<IActionResult> Update(int categoryId)
        {
            ResponseDto response = await _CategoryService.GetById(categoryId);
            if (response.IsSuccess || response.Result != null)
            {
                CategoryDto? category = JsonConvert.DeserializeObject<CategoryDto>(response.Result.ToString());
                return View(category);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(CategoryDto CategoryDto)
        {
            var obj = await _CategoryService.Update(CategoryDto);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("[controller]/Delete/{categoryId?}")]
        public async Task<IActionResult> Delete(int categoryId)
        {
            ResponseDto response = await _CategoryService.GetById(categoryId);
            if (response.IsSuccess || response.Result != null)
            {
                CategoryDto? company = JsonConvert.DeserializeObject<CategoryDto>(response.Result.ToString());
                return View(company);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CategoryDto CategoryDto)
        {
            var obj = await _CategoryService.Delete(CategoryDto.Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Micro.Web/Controllers/CompanyController.cs
using Micro.Web.Models.Dto;
using Micro.Web.Services.IServices;
using Micro.Web.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Micro.Web.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _CompanyService;
        public CompanyController(ICompanyService companyService)
        {
            _CompanyService = companyService;
        }
        [Authorize(Roles =SD.RoleCustomer)]
        public async Task<IActionResult> Index()
        {
            ResponseDto response = await _CompanyService.Get();
             if (response.IsSuccess && response.Result != null)
            {
                List<CompanyDto> companies = JsonConvert.DeserializeObject<List<CompanyDto>>(response.Result.ToString());
                return View(companies);
            }
            else
            {
                return RedirectToAction("Index","Home");
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CompanyDto companyDto)
        {
            _CompanyService.Create(companyDto);
            return View();
        }
        [HttpGet("[controller]/Update/{companyId?}")]
        public async Task<IActionResult> Update(int companyId)
        {
            ResponseDto response = await _CompanyService.GetById(companyId);
            if (response.IsSuccess || response.Result != null)
            { 
                CompanyDto? company = JsonConvert.DeserializeObject<CompanyDto>(response.Result.ToString());
                return View(company);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(CompanyDto companyDto)
        {
            var obj = await _CompanyService.Update(companyDto);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("[controller]/Delete/{companyId?}")]
        public async Task<IActionResult> Delete(int companyId)
        {
            ResponseDto response = await _CompanyService.GetById(companyId);
            if (response.IsSuccess || response.Result != null)
            {
                CompanyDto? company = JsonConvert.DeserializeObject<CompanyDto>(response.Result.ToString());
                return View(company);
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CompanyDto companyDto)
        {
            var obj = await _CompanyService.Delete(companyDto.Id);
            return RedirectToAction(nameof(Index));
        }


    }
}

Micro.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace Micro.Web.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Update()
        {
            return View();
        }
        public IActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(int a)
        {
            return View();
        }

    }
}

Micro.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Micro.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Micro.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Micro.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Company</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link " href="#">Hello @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Micro.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>